images: data/voc/images.txt             # path to image list as txt file
images_eval: data/voc_test/images.txt   # path to image list as txt file

split_ratio: 
  train: 0.8   # ratio of training images
  valid: 0.2   # ratio of validation images

num_classes: 20

# class names
class_names: [
'aeroplane',
'bicycle',
'bird',
'boat',
'bottle',
'bus',
'car',
'cat',
'chair',
'cow',
'diningtable',
'dog',
'horse',
'motorbike',
'person',
'pottedplant',
'sheep',
'sofa',
'train',
'tvmonitor',
]